version: "3.0"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.39.0
    container_name: jaeger
    hostname: jaeger
    #image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"
    #TODO figure out how to get this to work...
    #Jaeger prometheus integration to pull basic metrics into Jaeger.
    #Prometheus instance still has all metrics (Jager stuff is experimental)
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    #environment:
    #  - METRICS_STORAGE_TYPE=prometheus
    #  - PROMETHEUS_SERVER_URL=http://prometheus:9090
    #  - PROMETHEUS_SERVER_URL=http://host.docker.internal:9464
  prometheus:
    image: prom/prometheus:v2.40.2
    container_name: prometheus
    hostname: prometheus
    #image: prom/prometheus:latest
    #hostname: prometheus
    #user: "1000:1000"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      #Enable to preserve prometheus configs and data, if using this probably need to set the user above
      #- ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
    #- "9464:9464"
    extra_hosts:
      - "host.docker.internal:host-gateway"
