version: "3.0"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.39.0
    #image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"
  prometheus:
    image: prom/prometheus:v2.40.2
    #image: prom/prometheus:latest
    #user: "1000:1000"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      #Enable to preserve prometheus configs and data, if using this probably need to set the user above
      #- ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
    #- "9464:9464"
    extra_hosts:
      - "host.docker.internal:host-gateway"
