# Exports to New Relic's EU OTLP endpoints. For US accounts use https://otlp.nr-data.net.
# NEW_RELIC_LICENSE_KEY must be set in the environment (the ingest license key, e.g. eu01xx...NRAL).
# Activate with --spring.profiles.active=newrelic
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=https://otlp.eu01.nr-data.net/v1/metrics
management.otlp.metrics.export.headers.api-key=${NEW_RELIC_LICENSE_KEY}
management.otlp.metrics.export.step=10s
management.tracing.export.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=https://otlp.eu01.nr-data.net/v1/traces
management.opentelemetry.tracing.export.otlp.headers.api-key=${NEW_RELIC_LICENSE_KEY}

# Carried over 1:1 from the old agent-new-relic.properties
management.opentelemetry.tracing.limits.max-attribute-value-length=4095
management.opentelemetry.resource-attributes.service.namespace=vaadinkits
management.opentelemetry.resource-attributes.service.instance.id=kittest-app
